# -*- coding: utf-8 -*-
"""copy_dari_09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMbErhorqo7ubxzsVyggbexWQSkcMNDF

1
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U "transformers==4.45.2" datasets accelerate evaluate rouge-score sentencepiece indobenchmark-toolkit "peft==0.10.0" sacremoses nltk

import os, re, random, numpy as np, pandas as pd, torch, warnings, gc, glob, shutil, json
warnings.filterwarnings("ignore", category=FutureWarning)

SEED = 42
random.seed(SEED); np.random.seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Turbo matmul (Ampere+)
try:
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.set_float32_matmul_precision("high")
except Exception:
    pass

# === Helper: logging & optional save ===
SAVE_INTERMEDIATE = True  # <-- ubah ke True jika ingin save CSV setiap tahap
def maybe_save(df: pd.DataFrame, path: str, name: str):
    if SAVE_INTERMEDIATE:
        df.to_csv(path, index=False, encoding="utf-8")
        print(f"[SAVE] {name}: {path}")

def show_df_info(title: str, df: pd.DataFrame, n=2):
    print(f"\n[{title}] shape={df.shape}")
    print(df.head(n))

"""# menghubungkan ke drive email"""

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)

# Path dasar
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009"
DATA_DIR = f"{BASE_DIR}/data"
OUT_DIR  = f"{BASE_DIR}/outputs/indobart-v2-detik"
DATASET_DIR  = f"{BASE_DIR}/dataset"

# Buat folder jika belum ada
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(DATASET_DIR, exist_ok=True)

# Path file CSV
DATA_PATH = f"{DATA_DIR}/all_dataset_fix.csv"  # kalau file ada di root Colab
print("DATA_PATH:", DATA_PATH)
print("DATASET_DIR:", DATASET_DIR)

"""# menggabungkan dataset"""

import pandas as pd
import os

# Path folder dataset
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009"
DATASET_DIR = f"{BASE_DIR}/dataset"

# --- Ganti nama file sesuai nama asli di Google Drive ---
# (Pastikan penulisan nama file dan ekstensi sama persis)
mc_file   = os.path.join(DATASET_DIR, "MC_cleaned_gold_summary_fix_clean - MC_cleaned_gold_summary_fix_clean.csv")
mmc_file  = os.path.join(DATASET_DIR, "MMC_fix.csv")
detik_file = os.path.join(DATASET_DIR, "detik_clean_gold_summaryr (3).csv")

# Pastikan file benar-benar ada
for f in [mc_file, mmc_file, detik_file]:
    if not os.path.exists(f):
        print(f"⚠️  File tidak ditemukan: {f}")

# Gabungkan ketiga dataset (gunakan ignore_index agar index disusun ulang)
df_all = pd.concat([
    pd.read_csv(mc_file),
    pd.read_csv(mmc_file),
    pd.read_csv(detik_file)
], ignore_index=True)

# Simpan hasil gabungan
output_path = os.path.join(DATASET_DIR, "all_dataset_fix.csv")
df_all.to_csv(output_path, index=False)

print("✅ Dataset gabungan disimpan di:", output_path)
print("📊 Total baris gabungan:", len(df_all))

"""# hilangkan duplikat berdasarkan text & summary"""

import pandas as pd
import numpy as np

# Pastikan variabel path sudah benar
# DATA_PATH = "..."   # isi sesuai lokasi file
# DATA_DIR  = "..."

# --- Load fleksibel ---
try:
    df = pd.read_csv(DATA_PATH, sep=None, engine="python")
except Exception:
    try:
        df = pd.read_csv(DATA_PATH, sep=";")
    except Exception:
        df = pd.read_csv(DATA_PATH)

# --- Header normalization & mapping ---
# Hapus BOM dan spasi agar nama kolom bersih
df.columns = [str(c).replace("\ufeff", "").strip() for c in df.columns]

rename_map = {}
if "Isi Berita" in df.columns:
    rename_map["Isi Berita"] = "text"
if "gold_summary" in df.columns:
    rename_map["gold_summary"] = "summary"

print("Rename map :", rename_map)              # optional debug
df = df.rename(columns=rename_map)
print("Kolom akhir:", df.columns.tolist())     # optional debug

# Pastikan kolom utama sudah ada
assert "text" in df.columns and "summary" in df.columns, \
       f"Kolom tidak ditemukan: {list(df.columns)}"

# --- Bersih dasar ---
orig_len = len(df)
df["text"]    = df["text"].astype(str).str.strip()
df["summary"] = df["summary"].astype(str).str.strip()

df = (
    df.replace({"": np.nan})
      .dropna(subset=["text", "summary"])
      .drop_duplicates(subset=["text", "summary"])
      .reset_index(drop=True)
)

print(f"[CLEAN] rows: {orig_len} -> {len(df)}")

# --- Info & simpan ---
# Jika show_df_info/maybe_save tidak ada, definisikan dulu atau komentar barisnya
def show_df_info(tag, dataf):
    print(f"[INFO] {tag}: shape={dataf.shape}, cols={list(dataf.columns)}")

def maybe_save(dataf, path, tag):
    dataf.to_csv(path, index=False)
    print(f"[SAVE] {tag} -> {path}")

show_df_info("RAW_CLEAN", df)
maybe_save(df, f"{DATA_DIR}/step2_raw_clean.csv", "RAW_CLEAN")

"""# hilangkan duplikat berdasarkan text & summary"""

df_nodup = (
    df.drop_duplicates(subset=["text", "summary"])  # hilangkan duplikat berdasarkan text & summary
      .reset_index(drop=True)
)

print(f"[DEDUP] rows: {len(df)} -> {len(df_nodup)}")

# Simpan hasil dedup
maybe_save(df_nodup, f"{DATA_DIR}/step3_no_duplicates.csv", "DEDUP")

"""# lead-like ratio adalah Seberapa mirip ringkasan (summary) dengan bagian awal berita (lead)"""

# Robust sentence splitter (NLTK + fallback)
import re
import nltk
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    try: nltk.download('punkt_tab')
    except Exception: pass

def sent_tokenize_safe(text: str):
    try:
        from nltk.tokenize import sent_tokenize
        return sent_tokenize(text)
    except Exception:
        text = re.sub(r'\s+', ' ', str(text).strip())
        if not text: return []
        return re.split(r'(?<=[.!?])\s+(?=[A-Za-zÀ-ÖØ-öø-ÿ0-9"“‘])', text)

def norm(s): return re.sub(r"\s+"," ", str(s).lower().strip())

def is_lead_like(text, summ, k_sents=3):
    sents = sent_tokenize_safe(text)
    lead  = " ".join(sents[:k_sents]) if sents else str(text)
    return norm(summ) in norm(lead)

mask_lead = df.apply(lambda r: is_lead_like(r["text"], r["summary"], k_sents=3), axis=1)
lead_ratio = float(mask_lead.mean())
print(f"[LEAD DETECT] lead-like ratio: {lead_ratio:.2%}")

df_lead = df[mask_lead].copy()
df_keep = df[~mask_lead].copy()
print(f"[SPLIT] lead-like: {len(df_lead)} | keep: {len(df_keep)}")
show_df_info("LEAD_SUBSET", df_lead)

tmp = df.copy(); tmp["lead_like"] = mask_lead
maybe_save(tmp, f"{DATA_DIR}/step4_flag_lead.csv", "FLAG_LEAD")

"""# mengecek kualitas ringkasan (summary) dari dataset sebelum digunakan untuk training."""

def jaccard(a, b):
    A, B = set(norm(a).split()), set(norm(b).split())
    return len(A & B) / max(1, len(A | B))

def ok_summary(row, min_w=12, max_w=120, jacc_src_th=0.8):
    # gunakan ringkasan asli (summary) karena summary_bt tidak ada
    summ, src = row["summary"], row["text"]
    n = len(str(summ).split())
    return (min_w <= n <= max_w) and (jaccard(src[:600], summ) < jacc_src_th)

if len(df_lead):
    # langsung cek kelayakan ringkasan asli
    df_lead["summary_ok"] = df_lead.apply(ok_summary, axis=1)
    ok_ratio = float(df_lead["summary_ok"].mean())
    print(f"[FILTER] ok ratio: {ok_ratio:.2%}")
    # jika lolos filter tetap pakai summary, kalau tidak juga tetap summary
    df_lead["summary_final"] = df_lead["summary"]
else:
    df_lead["summary_final"] = df_lead["summary"]

# gabungkan dengan data yang memang disimpan
df_keep = df_keep.assign(summary_final=lambda d: d["summary"])
df_new = pd.concat(
    [
        df_keep[["text", "summary_final"]],
        df_lead[["text", "summary_final"]],
    ],
    ignore_index=True
).rename(columns={"summary_final": "summary"}).reset_index(drop=True)

print(f"[MERGE] df_new: {df_new.shape}")
show_df_info("DF_NEW", df_new)
maybe_save(df_new, f"{DATA_DIR}/step5c_df_new.csv", "DF_NEW")

"""# Dataset dibagi menjadi tiga bagian menggunakan metode random split dengan rasio 80:10:10. numpy.RandomState"""

# --- RANDOM SPLIT 80/10/10 UNTUK DATA TEKS ---
import numpy as np

rng = np.random.RandomState(SEED)
rand_vals = rng.rand(len(df_new))

train_mask = rand_vals < 0.8
valid_mask = (rand_vals >= 0.8) & (rand_vals < 0.9)
test_mask  = rand_vals >= 0.9

train_df = df_new[train_mask].reset_index(drop=True)
valid_df = df_new[valid_mask].reset_index(drop=True)
test_df  = df_new[test_mask].reset_index(drop=True)

split_type = "random 80/10/10"

print(f"[SPLIT] {split_type} → train={len(train_df)} | valid={len(valid_df)} | test={len(test_df)}")

maybe_save(train_df, f"{DATA_DIR}/step6_train.csv", "TRAIN")
maybe_save(valid_df, f"{DATA_DIR}/step6_valid.csv", "VALID")
maybe_save(test_df,  f"{DATA_DIR}/step6_test.csv", "TEST")

"""# Tokenizer IndoBART menggunakan IndoNLGTokenizer"""

from datasets import Dataset, DatasetDict
from transformers import AutoModelForSeq2SeqLM
from indobenchmark import IndoNLGTokenizer
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
import types

MODEL_NAME = "indobenchmark/indobart-v2"
MAX_INPUT_LEN = 800
MAX_TARGET_LEN = 100
BATCH_SIZE = 2  # kecilin batch size
GRADIENT_ACCUMULATION_STEPS = 4  # tetap jaga effective batch besar


ds = DatasetDict({
    "train": Dataset.from_pandas(train_df),
    "validation": Dataset.from_pandas(valid_df),
})

tokenizer = IndoNLGTokenizer.from_pretrained(MODEL_NAME)
def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self, encoded_inputs,
        padding=padding, max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of,
        return_attention_mask=return_attention_mask,
        return_tensors=return_tensors, verbose=verbose,
    )
tokenizer.pad = types.MethodType(_compat_pad, tokenizer)

base_model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(device)
if tokenizer.pad_token is None:
    if tokenizer.eos_token: tokenizer.pad_token = tokenizer.eos_token
    else:
        tokenizer.add_special_tokens({"pad_token": "[PAD]"})
        base_model.resize_token_embeddings(len(tokenizer))

print("[TOKENIZER] pad_token:", tokenizer.pad_token, "| bos:", tokenizer.bos_token, "| eos:", tokenizer.eos_token)

"""10"""

# ============================================================
# 🔹 CEK JUMLAH TOKEN INPUT (BERITA) DAN OUTPUT (RINGKASAN)
# ============================================================

import pandas as pd
from indobenchmark import IndoNLGTokenizer
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
import types

# ============================================================
# 1️⃣ Load dataset dari Drive
# ============================================================
train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Summary009/data/step6_train.csv")

# Pastikan nama kolom teks sumber dan ringkasan benar
# Misal kolom: "text" untuk berita, "summary" untuk ringkasan
kolom_input = "text"
kolom_summary = "summary"

# ============================================================
# 2️⃣ Load tokenizer IndoBART
# ============================================================
MODEL_NAME = "indobenchmark/indobart-v2"
tokenizer = IndoNLGTokenizer.from_pretrained(MODEL_NAME)

def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self, encoded_inputs,
        padding=padding, max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of,
        return_attention_mask=return_attention_mask,
        return_tensors=return_tensors, verbose=verbose,
    )
tokenizer.pad = types.MethodType(_compat_pad, tokenizer)

# ============================================================
# 3️⃣ Fungsi untuk menghitung jumlah token
# ============================================================
def hitung_token(teks):
    tokens = tokenizer(str(teks), return_tensors="pt", truncation=False)
    return len(tokens["input_ids"][0])

# ============================================================
# 4️⃣ Hitung token untuk teks input dan summary
# ============================================================
train_df["token_input"] = train_df[kolom_input].apply(hitung_token)
train_df["token_summary"] = train_df[kolom_summary].apply(hitung_token)

# ============================================================
# 5️⃣ Tampilkan statistik
# ============================================================
print("\n📊 Statistik Panjang Token Input (Berita):")
print("Rata-rata :", round(train_df['token_input'].mean(), 2))
print("Maksimum  :", train_df['token_input'].max())
print("Minimum   :", train_df['token_input'].min())

print("\n📘 Statistik Panjang Token Output (Ringkasan):")
print("Rata-rata :", round(train_df['token_summary'].mean(), 2))
print("Maksimum  :", train_df['token_summary'].max())
print("Minimum   :", train_df['token_summary'].min())

print("\n🧩 Contoh data token input vs summary:")
print(train_df[[kolom_input, "token_input", kolom_summary, "token_summary"]].head())

# ============================================================
# 6️⃣ Cek berapa yang melebihi batas model (800 input / 100 summary)
# =========

"""# parameter untuk fine-tuning LoRA (PEFT)"""

from peft import LoraConfig, get_peft_model, TaskType
peft_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=16, lora_alpha=32, lora_dropout=0.05,
    bias="none",
    target_modules=["q_proj","k_proj","v_proj","o_proj","fc1","fc2"],
)
model = get_peft_model(base_model, peft_cfg)
model.print_trainable_parameters()

"""# training IndoBART"""

def lead_drop(text, p=0.3, max_drop=2):
    sents = sent_tokenize_safe(text)
    if random.random() < p and len(sents) > 0:
        k = min(len(sents), random.randint(1, max_drop))
        return " ".join(sents[k:])
    return text

def preprocess_train(batch):
    texts = [lead_drop(t, p=0.3, max_drop=2) for t in batch["text"]]
    mi = tokenizer(texts, max_length=MAX_INPUT_LEN, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["summary"], max_length=MAX_TARGET_LEN, truncation=True)
    mi["labels"] = labels["input_ids"]
    return mi

def preprocess_valid(batch):
    mi = tokenizer(batch["text"], max_length=MAX_INPUT_LEN, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["summary"], max_length=MAX_TARGET_LEN, truncation=True)
    mi["labels"] = labels["input_ids"]
    return mi

tokenized_train = ds["train"].map(preprocess_train, batched=True, remove_columns=ds["train"].column_names)
tokenized_valid = ds["validation"].map(preprocess_valid, batched=True, remove_columns=ds["validation"].column_names)
print("[TOKENIZED] train:", tokenized_train.shape, "| valid:", tokenized_valid.shape)

from transformers import DataCollatorForSeq2Seq
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

import evaluate
rouge = evaluate.load("rouge")

def safe_batch_decode(seqs, skip_special_tokens=True):
    return [tokenizer.decode(s.tolist() if hasattr(s, "tolist") else s,
                             skip_special_tokens=skip_special_tokens) for s in seqs]

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple): preds = preds[0]
    decoded_preds = safe_batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = safe_batch_decode(labels, skip_special_tokens=True)
    decoded_preds  = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]
    res = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v*100, 2) for k,v in res.items()}

"""# fine-tuning IndoBART"""

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, GenerationConfig

# --- konfigurasi generate (lebih fokus kualitas, bukan kecepatan) ---
model.generation_config = GenerationConfig(
    do_sample=False,              # 💡 nonaktifkan sampling agar lebih deterministik
    num_beams=4,                  # 💡 beam search = kualitas ringkasan naik signifikan
    top_p=0.9,
    temperature=0.8,
    top_k=40,
    no_repeat_ngram_size=3,
    repetition_penalty=1.2,
    length_penalty=2.0,           # 💡 penalti panjang biar ringkasan lebih padat
    max_new_tokens=128,
    min_new_tokens=25,
    early_stopping=True,
    decoder_start_token_id=(getattr(model.config, "decoder_start_token_id", None)
                            or getattr(tokenizer, "bos_token_id", None)
                            or getattr(tokenizer, "eos_token_id", None)),
)

# === subset validasi tetap ===
eval_subset_size = len(tokenized_valid)
eval_for_train = tokenized_valid.select(range(eval_subset_size))
print(f"[EVAL SUBSET] {eval_subset_size} samples dari valid untuk evaluasi berkala")

# --- training args (dioptimasi) ---
training_args = Seq2SeqTrainingArguments(
    output_dir=OUT_DIR,
    evaluation_strategy="steps",
    save_strategy="steps",
    eval_steps=800,
    save_steps=800,
    logging_steps=100,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    dataloader_num_workers=2,
    group_by_length=True,

    learning_rate=5e-5,           # 💡 turunkan agar lebih stabil dan tidak overfit
    warmup_ratio=0.1,
    weight_decay=0.01,

    num_train_epochs=5,           # 💡 tambahkan 1 epoch lagi (model belum konvergen di 3)
    lr_scheduler_type="linear",   # 💡 jadikan decay linear
    predict_with_generate=True,
    generation_num_beams=4,       # 💡 samakan dengan beam search
    fp16=(device == "cuda"),
    report_to=["none"],
    save_total_limit=3,

    load_best_model_at_end=True,  # 💡 otomatis pilih model val terbaik
    metric_for_best_model="rougeLsum",
    greater_is_better=True,
)

# --- Patch IndoNLGTokenizer agar tidak error saat save ---
def _dummy_save_vocabulary(self, save_directory, filename_prefix=None):
    return (save_directory, [])

tokenizer.save_vocabulary = types.MethodType(_dummy_save_vocabulary, tokenizer)

# --- Trainer setup ---
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=eval_for_train,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

train_metrics = trainer.train().metrics
print("[TRAIN METRICS]", json.dumps(
    {k: float(v) if isinstance(v, (int, float, np.floating)) else str(v)
     for k, v in train_metrics.items()}, indent=2))

"""# evaluasi final validasi"""

model.generation_config.max_new_tokens = MAX_TARGET_LEN
model.generation_config.min_new_tokens = max(16, MAX_TARGET_LEN//4)

full_eval = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_valid,
    tokenizer=None,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)
eval_metrics = full_eval.evaluate()
print("[FULL EVAL]", json.dumps({k: float(v) if isinstance(v, (int, float, np.floating)) else str(v) for k,v in eval_metrics.items()}, indent=2))

"""# Save Model IndoBART"""

# === SAVE FINAL MODEL ke Google Drive ===
import os, torch, shutil
from datetime import datetime
from transformers import AutoModelForSeq2SeqLM

# Pastikan Drive sudah ter-mount & BASE_DIR sudah didefinisikan sebelumnya:
# BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary01"

MODELS_DIR = os.path.join(BASE_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

RUN_TAG   = datetime.now().strftime("%Y%m%d-%H%M%S")
FINAL_DIR = os.path.join(MODELS_DIR, f"indobart-v2-detik-final-{RUN_TAG}")
os.makedirs(FINAL_DIR, exist_ok=True)
print("[FINAL_DIR]", FINAL_DIR)

# 1) Merge LoRA -> model standar
print("[MERGE] Menggabungkan adapter LoRA ke base model…")
model = model.merge_and_unload().to(device)

# 2) Simpan model (sementara) ke Drive
model.save_pretrained(FINAL_DIR, safe_serialization=True)
if getattr(model, "generation_config", None) is not None:
    model.generation_config.save_pretrained(FINAL_DIR)
print(f"[SAVE] Model sementara disimpan ke: {FINAL_DIR}")

# 3) Repack kunci embedding agar bersih saat load (hindari 'missing keys')
st_path = os.path.join(FINAL_DIR, "model.safetensors")
pt_path = os.path.join(FINAL_DIR, "pytorch_model.bin")
if os.path.exists(st_path):
    from safetensors.torch import load_file as safe_load
    sd = safe_load(st_path)
else:
    sd = torch.load(pt_path, map_location="cpu")

def _get_any(d, keys):
    for k in keys:
        if k in d: return d[k]
    return None

shared = _get_any(sd, ["model.shared.weight","shared.weight","model.model.shared.weight"])
enc    = _get_any(sd, ["model.encoder.embed_tokens.weight","model.model.encoder.embed_tokens.weight"])
dec    = _get_any(sd, ["model.decoder.embed_tokens.weight","model.model.decoder.embed_tokens.weight"])

if shared is not None:
    sd.setdefault("model.encoder.embed_tokens.weight", shared)
    sd.setdefault("model.decoder.embed_tokens.weight", shared)
    sd.setdefault("lm_head.weight", shared)
else:
    if enc is not None: sd.setdefault("model.encoder.embed_tokens.weight", enc)
    if dec is not None:
        sd.setdefault("model.decoder.embed_tokens.weight", dec)
        sd.setdefault("lm_head.weight", sd.get("lm_head.weight", dec))

missing, unexpected = model.load_state_dict(sd, strict=False)
print("[REPACK] missing:", missing, "| unexpected:", unexpected)

# 4) Simpan ulang (final) ke Drive + verify
model.save_pretrained(FINAL_DIR, safe_serialization=True)
if getattr(model, "generation_config", None) is not None:
    model.generation_config.save_pretrained(FINAL_DIR)

# (opsional) salin config.json dari OUT_DIR jika ada
cfg_src = os.path.join(OUT_DIR, "config.json")
if os.path.exists(cfg_src):
    shutil.copy(cfg_src, os.path.join(FINAL_DIR, "config.json"))

_ = AutoModelForSeq2SeqLM.from_pretrained(FINAL_DIR)
print(f"[CHECK] Clean load OK. Model FINAL disimpan di Drive: {FINAL_DIR}")

"""# Inferensi dari TEKS BERITA (TEKS)"""

import torch
import types
from indobenchmark import IndoNLGTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
from typing import List

# === Path model fine-tuned ===
FINAL_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009/models/indobart-v2-detik-final-20251201-061311"
# === Device ===
device = "cuda" if torch.cuda.is_available() else "cpu"

# === Load model fine-tuned ===
print("Loading model...")
model = AutoModelForSeq2SeqLM.from_pretrained(FINAL_DIR).to(device)
model.eval()
print("✅ Model loaded on", device)

# === Load tokenizer original IndoBART ===
tokenizer = IndoNLGTokenizer.from_pretrained("indobenchmark/indobart-v2")

# === Patch fungsi pad supaya kompatibel dengan transformers baru ===
def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self,
        encoded_inputs,
        padding=padding,
        max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of,
        return_attention_mask=return_attention_mask,
        return_tensors=return_tensors,
        verbose=verbose
    )

tokenizer.pad = types.MethodType(_compat_pad, tokenizer)

print("[TOKENIZER] pad_token:", tokenizer.pad_token, "| bos:", tokenizer.bos_token, "| eos:", tokenizer.eos_token)

# === Function chunking teks panjang ===
def chunk_text(text: str, tokenizer, max_input_length: int = 512, stride: int = 256) -> List[str]:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=False,
        add_special_tokens=False,
    )
    input_ids = inputs["input_ids"][0]
    total_len = input_ids.size(0)
    chunks = []

    for i in range(0, total_len, stride):
        end = min(i + max_input_length, total_len)
        chunk_ids = input_ids[i:end]
        chunk_text = tokenizer.decode(chunk_ids, skip_special_tokens=True)
        chunks.append(chunk_text)
        if end == total_len:
            break

    return chunks

# === Function ringkas 1 chunk ===
def summarize_chunk(text: str, model, tokenizer, device="cpu",
                    max_input_length: int = 800, max_output_length: int = 100) -> str:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=max_input_length,
        truncation=True,
        padding="max_length",
    ).to(device)

    with torch.no_grad():
        summary_ids = model.generate(
            inputs["input_ids"],
            num_beams=4,
            max_length=max_output_length,
            early_stopping=True,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
        )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# === Function ringkas teks panjang 1-3 kalimat + judul & tanggal opsional ===
def summarize_long_text(
    text: str,
    model,
    tokenizer,
    device="cpu",
    max_input_length: int = 800,
    stride: int = 400,
    max_output_length: int = 100,
    num_sentences: int = 3,
    title: str = None,   # judul opsional
    date: str = None     # tanggal opsional
) -> str:
    # --- Bagi teks menjadi chunk ---
    chunks = chunk_text(text, tokenizer, max_input_length=max_input_length, stride=stride)
    summaries = []

    for i, chunk in enumerate(chunks):
        print(f"⚡ Ringkas chunk {i+1}/{len(chunks)} ...")
        summary = summarize_chunk(
            chunk, model, tokenizer, device=device,
            max_input_length=max_input_length,
            max_output_length=max_output_length
        )
        summaries.append(summary)

    final_summary = " ".join(summaries).strip()

   # --------- NORMALISASI KALIMAT ---------
    text = final_summary.replace("\n", " ")
    text = " ".join(text.split())   # hilangkan spasi berlebih

    # --------- PISAH KALIMAT MODEL ---------
    sentences = [s.strip() for s in text.split(".") if len(s.strip()) > 0]

    # --------- RINGKAS JIKA TERLALU PANJANG ---------
    if len(sentences) > 0:
        # Ambil hanya klausa pertama dari kalimat pertama
        first = sentences[0]

        # Jika kalimat terlalu panjang, potong di koma pertama
        if "," in first and len(first) > 110:
            first = first.split(",")[0]

        # Ambil maksimum 18–22 kata agar tetap 1 kalimat padat
        words = first.split()
        if len(words) > 22:
            first = " ".join(words[:22])

        final_summary = first
    else:
        final_summary = text

    # --------- TAMBAH TITIK DI AKHIR ---------
    if not final_summary.endswith("."):
        final_summary += "."

    # --- Susun header (judul + tanggal kalau ada) ---
    header_parts = []
    if title:
        header_parts.append(f"📰 {title}")
    if date:
        header_parts.append(f"📅 {date}")

    header = "\n".join(header_parts)
    if header:
        final_summary = f"{header}\n{final_summary}"

    return final_summary


# === Contoh penggunaan ===

article_title = "BPBD Imbau Warga Bantaran Sungai Tingkatkan Kewaspadaan Banjir Kiriman"
article_date  = "30 November 2025"
article_text = """
MEDIA CENTER, Palangka Raya – Badan Penanggulangan Bencana Daerah (BPBD) Kota Palangka Raya mengimbau masyarakat yang tinggal di bantaran Sungai Kahayan dan Rungan untuk meningkatkan kewaspadaan menyusul adanya potensi banjir kiriman akibat meningkatnya intensitas hujan di wilayah hulu.

Analis Kebencanaan BPBD Kota Palangka Raya, Balap Sipet menjelaskan bahwa kenaikan debit air sungai terjadi terutama karena curah hujan lebat di daerah hulu yang menjadi bagian dari Daerah Aliran Sungai (DAS) Kahayan. Meski kenaikan debit saat ini belum dalam kategori mengkhawatirkan, tren peningkatan tetap harus diwaspadai.

“Mulainya kenaikan debit air sungai sebagian besar disebabkan hujan sedang hingga lebat di wilayah hulu DAS Kahayan. Ini menjadi indikator awal potensi banjir kiriman yang perlu diantisipasi,” ujarnya, Minggu (30/11/2025).

BPBD melakukan pemantauan rutin di beberapa titik strategis, seperti Kelurahan Pahandut, Palangka, dan Bereng Bengkel. Hasil pantauan terbaru menunjukkan adanya peningkatan debit meskipun belum berdampak besar terhadap aktivitas masyarakat. Namun demikian, genangan ringan mulai terlihat di beberapa jalan lingkungan.

Selain pemantauan debit air, BPBD memperkuat koordinasi dengan Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) untuk memperoleh informasi perkiraan cuaca yang lebih akurat. Koordinasi ini bertujuan memastikan langkah mitigasi dapat dilakukan lebih cepat dan tepat sasaran.

“Kami terus berkoordinasi dengan BMKG mengenai prospek cuaca harian. Informasi ini penting untuk memprediksi kemungkinan naiknya debit air dalam beberapa hari ke depan,” terangnya.

Sebagai langkah antisipasi, BPBD juga melakukan edukasi langsung kepada warga kawasan bantaran sungai. Warga diminta menyiapkan langkah-langkah keselamatan dasar, seperti tidak meletakkan barang elektronik di lantai, memeriksa aliran listrik, hingga memastikan akses keluar rumah dalam keadaan aman jika terjadi genangan.

“Daerah kita sering diguyur hujan dengan intensitas bervariasi. Jika hujan di wilayah hulu meningkat signifikan, Kota Palangka Raya sangat mungkin menerima banjir kiriman. Karena itu masyarakat harus tetap siaga,” jelas Balap Sipet.

BPBD menegaskan bahwa kesiapsiagaan merupakan tanggung jawab bersama. Dengan pemantauan ketat, edukasi yang berkelanjutan, dan koordinasi lintas sektor, diharapkan potensi dampak dari banjir kiriman dapat diminimalkan.

“Situasi ini masih terkendali, tetapi masyarakat jangan lengah. Kewaspadaan dini adalah kunci untuk mengurangi risiko,” pungkasnya. (MC Kota Palangka Raya/Nitra/ndk)
"""
summary = summarize_long_text(
    article_text,
    model,
    tokenizer,
    device=device,
    max_output_length=150,
    num_sentences=4,
    title=article_title,   # judul asli dimasukkan di sini
    date=article_date

)

print("\n=== HASIL RINGKASAN ===")
print(summary)

import torch
import types
from indobenchmark import IndoNLGTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
from typing import List
import re # Import re for sentence splitting

# === Path model fine-tuned ===
FINAL_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009/models/indobart-v2-detik-final-20251201-061311"
# === Device ===
device = "cuda" if torch.cuda.is_available() else "cpu"

# === Load model fine-tuned ===
print("Loading model...")
model = AutoModelForSeq2SeqLM.from_pretrained(FINAL_DIR).to(device)
model.eval()
print("✅ Model loaded on", device)

# === Load tokenizer original IndoBART ===
tokenizer = IndoNLGTokenizer.from_pretrained("indobenchmark/indobart-v2")

# === Patch fungsi pad supaya kompatibel dengan transformers baru ===
def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self,
        encoded_inputs,
        padding=padding,
        max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of,
        return_attention_mask=return_attention_mask,
        return_tensors=return_tensors,
        verbose=verbose
    )

tokenizer.pad = types.MethodType(_compat_pad, tokenizer)

print("[TOKENIZER] pad_token:", tokenizer.pad_token, "| bos:", tokenizer.bos_token, "| eos:", tokenizer.eos_token)

# === Function chunking teks panjang ===
def chunk_text(text: str, tokenizer, max_input_length: int = 512, stride: int = 256) -> List[str]:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=False,
        add_special_tokens=False,
    )
    input_ids = inputs["input_ids"][0]
    total_len = input_ids.size(0)
    chunks = []

    for i in range(0, total_len, stride):
        end = min(i + max_input_length, total_len)
        chunk_ids = input_ids[i:end]
        chunk_text = tokenizer.decode(chunk_ids, skip_special_tokens=True)
        chunks.append(chunk_text)
        if end == total_len:
            break

    return chunks

# === Function ringkas 1 chunk ===
def summarize_chunk(text: str, model, tokenizer, device="cpu",
                    max_input_length: int = 800, max_output_length: int = 100) -> str:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=max_input_length,
        truncation=True,
        padding="max_length",
    ).to(device)

    with torch.no_grad():
        summary_ids = model.generate(
            inputs["input_ids"],
            num_beams=4,
            max_length=max_output_length,
            early_stopping=True,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
        )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# === Function ringkas teks panjang 1-3 kalimat + judul & tanggal opsional ===
def summarize_long_text(
    text: str,
    model,
    tokenizer,
    device="cpu",
    max_input_length: int = 800,
    stride: int = 400,
    max_output_length: int = 100,
    num_sentences: int = 3,
    title: str = None,   # judul opsional
    date: str = None     # tanggal opsional
) -> str:
    # --- Bagi teks menjadi chunk ---
    chunks = chunk_text(text, tokenizer, max_input_length=max_input_length, stride=stride)
    summaries = []

    for i, chunk in enumerate(chunks):
        print(f"⚡ Ringkas chunk {i+1}/{len(chunks)} ...")
        summary = summarize_chunk(
            chunk, model, tokenizer, device=device,
            max_input_length=max_input_length,
            max_output_length=max_output_length
        )
        summaries.append(summary)

    final_summary_combined = " ".join(summaries).strip()

    # ------------------- NORMALISASI & PISAH KALIMAT -------------------
    # Clean up whitespace and split into sentences more robustly
    clean_text = re.sub(r'\s+', ' ', final_summary_combined).strip()
    # Using a regex to split sentences, handling various punctuation and ensuring non-empty sentences
    sentences = re.split(r'(?<=[.!?])\s+', clean_text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # ------------------- AMBIL JUMLAH KALIMAT YANG DIINGINKAN -------------------
    selected_sentences = sentences[:num_sentences]
    processed_summary = " ".join(selected_sentences)

    # ------------------- TAMBAH TITIK DI AKHIR -------------------
    if processed_summary and not processed_summary.endswith('.'):
        processed_summary += '.'
    elif not processed_summary:
        processed_summary = final_summary_combined + '.' # Fallback if no sentences could be extracted

    # ------------------- SUSUN HEADER -------------------
    header_parts = []
    if title:
        header_parts.append(f"📰 {title}")
    if date:
        header_parts.append(f"📅 {date}")

    header = "\n".join(header_parts)
    if header:
        final_output_summary = f"{header}\n{processed_summary}"
    else:
        final_output_summary = processed_summary

    return final_output_summary



# === Contoh penggunaan ===
article_title = "Diklat Dasar SAR Angkatan 120 di Palangka Raya Resmi Dibuka"
article_date  = "29 November 2025"
article_text = """
MEDIA CENTER, Palangka Raya – Badan Nasional Pencarian dan Pertolongan (Basarnas) gelar Diklat Dasar Pencarian dan Pertolongan angkatan 120 di Kantor Pencarian dan Pertolongan (SAR) Palangka Raya, Jumat (28/11/2025).

Pelatihan Diklat SAR berlangsung selama 21 hari, mulai 27 November hingga 18 Desember 2025. Kegiatan ini diikuti oleh 23 peserta yang seluruhnya merupakan CPNS Kantor SAR Palangka Raya.

Diklat Dasar SAR dibuka secara resmi oleh Kepala Balai Sumber Daya Manusia Pencarian dan Pertolongan Basarnas, Heru Suhartanto.

Dalam sambutanya Heru menyampaikan, Diklat dasar ini dirancang untuk membekali para CPNS dengan pengetahuan dan keterampilan teknis di bidang pencarian dan pertolongan, sekaligus membentuk mentalitas, dedikasi, loyalitas, serta semangat militansi sebagai bagian dari Badan Nasional Pencarian dan Pertolongan.

“Selain peningkatan kemampuan teknis, pelatihan ini juga menjadi sarana pembentukan karakter agar para CPNS siap menghadapi tantangan tugas di lapangan dengan profesional dan tanggung jawab yang tinggi,” ucap Heru.

Sementara itu, Kepala Kantor SAR Palangka Raya AA. Ketut Alit Supartana berharap pelaksanaan Pelatihan dasar ini dapat berjalan dengan lancar sehingga tujuan dari pelatihan ini dapat tercapai.

“Selamat berlatih untuk para peserta, ambilah ilmu sebanyak-banyaknya dari para instruktur dan tetap semangat dalam menjalani pelatihan ini,” ucap Alit. (MC Kota Palangka Raya/Usep/ndk)
"""

# Ringkasan 1 kalimat
summary_1_sentence = summarize_long_text(
    article_text,
    model,
    tokenizer,
    device=device,
    max_output_length=150,
    num_sentences=1,
    title=article_title,
    date=article_date
)

print("\n=== HASIL RINGKASAN (1 Kalimat) ===")
print(summary_1_sentence)

# Ringkasan 3 kalimat
summary_3_sentences = summarize_long_text(
    article_text,
    model,
    tokenizer,
    device=device,
    max_output_length=150,
    num_sentences=3,
    title=article_title,
    date=article_date
)

print("\n=== HASIL RINGKASAN (3 Kalimat) ===")
print(summary_3_sentences)

"""# Inferensi dari TEKS BERITA ( URL)"""

# === Import scraping ===
import requests
from bs4 import BeautifulSoup
import re
import torch
import types
from indobenchmark import IndoNLGTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
from typing import List

def scrape_article(url: str):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"❌ Gagal ambil data: {e}")
        return None, None, None

    soup = BeautifulSoup(response.content, "html.parser")

    # Judul
    title = soup.find("title").get_text(strip=True) if soup.find("title") else "Tanpa Judul"

    # Tanggal
    match = re.search(r"\d{1,2}\s+\w+\s+\d{4}", soup.get_text())
    date = match.group(0) if match else None

    # Isi artikel
    container = soup.find("div", class_="single-content") or soup.find("div", class_="entry-content")
    paragraphs = container.find_all("p") if container else soup.find_all("p")

    clean_paragraphs = []
    for p in paragraphs:
        text = p.get_text(" ", strip=True)
        if text and len(text) > 50:
            # Bersihkan teks sampah umum
            text = re.sub(r"\b(Dibaca|Foto|©|All rights reserved|MTD|WF|DINAS KOMUNIKASI.*)\b.*", "", text)
            clean_paragraphs.append(text)

    article_text = " ".join(clean_paragraphs)
    return title, date, article_text


# === Path model fine-tuned ===
FINAL_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009/models/indobart-v2-detik-final-20251201-061311"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Loading model...")
model = AutoModelForSeq2SeqLM.from_pretrained(FINAL_DIR).to(device)
model.eval()
print("✅ Model loaded on", device)

tokenizer = IndoNLGTokenizer.from_pretrained("indobenchmark/indobart-v2")

# Patch fungsi pad
def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self, encoded_inputs, padding=padding, max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of, return_attention_mask=return_attention_mask,
        return_tensors=return_tensors, verbose=verbose
    )
tokenizer.pad = types.MethodType(_compat_pad, tokenizer)


# === Fungsi summarize ===
def chunk_text(text: str, tokenizer, max_input_length: int = 800, stride: int = 400) -> List[str]:
    inputs = tokenizer(text, return_tensors="pt", truncation=False, add_special_tokens=False)
    input_ids = inputs["input_ids"][0]
    total_len = input_ids.size(0)
    chunks = []
    for i in range(0, total_len, stride):
        end = min(i + max_input_length, total_len)
        chunk_ids = input_ids[i:end]
        chunk_text = tokenizer.decode(chunk_ids, skip_special_tokens=True)
        chunks.append(chunk_text)
        if end == total_len:
            break
    return chunks

def summarize_chunk(text: str, model, tokenizer, device="cpu", max_input_length: int = 800, max_output_length: int = 100) -> str:
    inputs = tokenizer(text, return_tensors="pt", max_length=max_input_length,
                       truncation=True, padding="max_length").to(device)
    with torch.no_grad():
        summary_ids = model.generate(
            inputs["input_ids"],
            num_beams=4,
            max_length=max_output_length,
            early_stopping=True,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
        )
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

def summarize_long_text(
    text: str,
    model,
    tokenizer,
    device="cpu",
    max_input_length: int = 800,
    stride: int = 400,
    max_output_length: int = 100,
    num_sentences: int = 3, # Default changed to 3 sentences for more detail
    title: str = None,   # judul opsional
    date: str = None     # tanggal opsional
) -> str:
    # --- Bagi teks menjadi chunk ---
    chunks = chunk_text(text, tokenizer, max_input_length=max_input_length, stride=stride)
    summaries = []

    for i, chunk in enumerate(chunks):
        print(f"⚡ Ringkas chunk {i+1}/{len(chunks)} ...")
        summary = summarize_chunk(
            chunk, model, tokenizer, device=device,
            max_input_length=max_input_length,
            max_output_length=max_output_length
        )
        summaries.append(summary)

    final_summary_combined = " ".join(summaries).strip()

    # ------------------- NORMALISASI & PISAH KALIMAT -------------------
    # Clean up whitespace and split into sentences more robustly
    clean_text = re.sub(r'\s+', ' ', final_summary_combined).strip()
    # Using a regex to split sentences, handling various punctuation and ensuring non-empty sentences
    sentences = re.split(r'(?<=[.!?])\s+', clean_text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # ------------------- AMBIL JUMLAH KALIMAT YANG DIINGINKAN -------------------
    selected_sentences = sentences[:num_sentences]
    processed_summary = " ".join(selected_sentences)

    # ------------------- TAMBAH TITIK DI AKHIR -------------------
    if processed_summary and not processed_summary.endswith('.'):
        processed_summary += '.'
    elif not processed_summary:
        processed_summary = final_summary_combined + '.' # Fallback if no sentences could be extracted

    # ------------------- SUSUN HEADER -------------------
    header_parts = []
    if title:
        header_parts.append(f"📰 {title}")
    if date:
        header_parts.append(f"📅 {date}")

    header = "\n".join(header_parts)
    if header:
        final_output_summary = f"{header}\n{processed_summary}"
    else:
        final_output_summary = processed_summary

    return final_output_summary


# === PEMANGGILAN DENGAN URL ===
url = "https://news.detik.com/berita/d-8237577/warga-aceh-ngadu-kebun-jagung-dihantam-banjir-ini-respons-prabowo"

title, date, article_text = scrape_article(url)

if article_text and len(article_text) > 200:
    print("\n=== HASIL SCRAPING BERITA ===")
    print(f"📰 Judul: {title}")
    if date:
        print(f"📅 Tanggal: {date}")
    print("\n📄 Isi Berita Asli:\n")
    print(article_text)
    print("="*90)

    print("\n=== HASIL RINGKASAN (1 Kalimat) ===")
    summary_1_sentence = summarize_long_text(article_text, model, tokenizer,
                                  device=device, max_output_length=100,
                                  num_sentences=1, # Set to 1 for concise summary
                                  title=title, date=date)
    print(summary_1_sentence)

    print("\n=== HASIL RINGKASAN (3 Kalimat) ===")
    summary_3_sentences = summarize_long_text(article_text, model, tokenizer,
                                  device=device, max_output_length=100,
                                  num_sentences=3, # Set to 3 for more informative summary
                                  title=title, date=date)
    print(summary_3_sentences)
else:
    print("⚠️ Artikel tidak valid atau teks terlalu pendek.")

"""# Evaluasi"""

# ============================================================
# 🧪 EVALUASI MODEL FINE-TUNED INDOBART-V2 DENGAN TEST SET
# ============================================================

import torch
import types
import pandas as pd
from tqdm import tqdm
from indobenchmark import IndoNLGTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers.tokenization_utils_base import PreTrainedTokenizerBase
import evaluate
from typing import List

# === Path model fine-tuned ===
FINAL_DIR = "/content/drive/MyDrive/Colab Notebooks/Summary009/models/indobart-v2-detik-final-20251201-061311"

# === Path test set CSV ===
PATH_TEST_CSV = "/content/drive/MyDrive/Colab Notebooks/Summary009/data/step6_test.csv"

# === Device ===
device = "cuda" if torch.cuda.is_available() else "cpu"

# === Load model fine-tuned ===
print("Loading model...")
model = AutoModelForSeq2SeqLM.from_pretrained(FINAL_DIR).to(device)
model.eval()
print("✅ Model loaded on", device)

# === Tambahkan konfigurasi generate default (biar tidak warning) ===
model.config.max_new_tokens = 100
model.config.early_stopping = True
model.config.no_repeat_ngram_size = 3
model.config.length_penalty = 1.0

# === Load tokenizer original IndoBART ===
tokenizer = IndoNLGTokenizer.from_pretrained("indobenchmark/indobart-v2")

# === Patch fungsi pad supaya kompatibel ===
def _compat_pad(self, encoded_inputs, padding=False, max_length=None,
                pad_to_multiple_of=None, return_attention_mask=None,
                return_tensors=None, verbose=True, **kwargs):
    return PreTrainedTokenizerBase.pad(
        self,
        encoded_inputs,
        padding=padding,
        max_length=max_length,
        pad_to_multiple_of=pad_to_multiple_of,
        return_attention_mask=return_attention_mask,
        return_tensors=return_tensors,
        verbose=verbose
    )
tokenizer.pad = types.MethodType(_compat_pad, tokenizer)

print("[TOKENIZER] pad_token:", tokenizer.pad_token, "| bos:", tokenizer.bos_token, "| eos:", tokenizer.eos_token)

# ============================================================
# 🔹 Fungsi bantu: Membagi teks panjang jadi beberapa chunk
# ============================================================
def chunk_text(text: str, tokenizer, max_input_length: int = 800, stride: int = 400) -> List[str]:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=False,
        add_special_tokens=False,
    )
    input_ids = inputs["input_ids"][0]
    total_len = input_ids.size(0)
    chunks = []

    for i in range(0, total_len, stride):
        end = min(i + max_input_length, total_len)
        chunk_ids = input_ids[i:end]
        chunk_text = tokenizer.decode(chunk_ids, skip_special_tokens=True)
        chunks.append(chunk_text)
        if end == total_len:
            break
    return chunks

# ============================================================
# 🔹 Fungsi bantu: Ringkas 1 chunk
# ============================================================
def summarize_chunk(text: str, model, tokenizer, device="cpu",
                    max_input_length: int = 800, max_output_length: int = 100) -> str:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=max_input_length,
        truncation=True,
        padding="max_length",
    ).to(device)

    with torch.no_grad():
        summary_ids = model.generate(
            inputs["input_ids"],
            num_beams=4,
            max_new_tokens=max_output_length,  # ✅ pakai max_new_tokens
            early_stopping=True,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
        )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# ============================================================
# 🔹 Fungsi utama: Ringkas teks panjang
# ============================================================
def summarize_long_text(
    text: str,
    model,
    tokenizer,
    device="cpu",
    max_input_length: int = 800,
    stride: int = 400,
    max_output_length: int = 100,
    num_sentences: int = 3,
) -> str:
    chunks = chunk_text(text, tokenizer, max_input_length=max_input_length, stride=stride)
    summaries = []

    for chunk in chunks:
        summary = summarize_chunk(
            chunk, model, tokenizer, device=device,
            max_input_length=max_input_length,
            max_output_length=max_output_length
        )
        summaries.append(summary)

    final_summary = " ".join(summaries).strip()
    sentences = final_summary.split(". ")
    if len(sentences) > num_sentences:
        sentences = sentences[:num_sentences]
    final_summary = ". ".join(sentences).strip()
    if not final_summary.endswith("."):
        final_summary += "."
    return final_summary

# ============================================================
# 📂 Load test set
# ============================================================
print(f"📂 Load test set dari CSV: {PATH_TEST_CSV}")
df = pd.read_csv(PATH_TEST_CSV)

assert "text" in df.columns and "summary" in df.columns, \
    f"Kolom CSV harus mengandung 'text' dan 'summary'. Kolom yang ada: {df.columns.tolist()}"

dataset_test = df.to_dict(orient="records")

# ============================================================
# 🚀 Evaluasi model dengan metrik ROUGE
# ============================================================
rouge = evaluate.load("rouge")
predictions, references = [], []

print("\n🚀 Mulai evaluasi test set...")
for sample in tqdm(dataset_test, desc="Evaluasi test set"):
    text = str(sample["text"]) if pd.notna(sample["text"]) else ""
    ref_summary = str(sample["summary"]) if pd.notna(sample["summary"]) else ""

    if not text.strip():
        predictions.append("")
        references.append(ref_summary)
        continue

    pred_summary = summarize_long_text(
        text,
        model,
        tokenizer,
        device=device,
        max_input_length=800,
        stride=400,
        max_output_length=100,
        num_sentences=4
    )

    predictions.append(pred_summary)
    references.append(ref_summary)

# ============================================================
# 📊 Hitung skor ROUGE
# ============================================================
results = rouge.compute(predictions=predictions, references=references)

print("\n=== HASIL EVALUASI DI TEST SET ===")
for key in ["rouge1", "rouge2", "rougeL", "rougeLsum"]:
    score = results[key]
    print(f"{key.upper()} (F1): {score:.4f}")

# ============================================================
# 💾 Simpan hasil ke CSV
# ============================================================
df_out = pd.DataFrame({
    "text": [s["text"] for s in dataset_test],
    "gold_summary": references,
    "pred_summary": predictions
})
save_path = "/content/drive/MyDrive/Colab Notebooks/Summary009/data/hasil_testset_predictions.csv"
df_out.to_csv(save_path, index=False)
print(f"\n✅ Hasil prediksi & ringkasan test set disimpan di: {save_path}")